/* generated by scripts/build-themes.mjs - do not edit */
export interface SiteTheme {
	id: string;
	label: string;
	dot: { bg: string; fg: string; accent: string };
}

export const DEFAULT_THEME = "catppuccin-mocha";

export const themes: SiteTheme[] = [
	{
		"id": "catppuccin-frappe",
		"label": "catppuccin frappe",
		"dot": {
			"bg": "#292c3c",
			"fg": "#d4dcf8",
			"accent": "#cea5e8"
		}
	},
	{
		"id": "catppuccin-macchiato",
		"label": "catppuccin macchiato",
		"dot": {
			"bg": "#1e2030",
			"fg": "#cad3f5",
			"accent": "#c6a0f6"
		}
	},
	{
		"id": "catppuccin-mocha",
		"label": "catppuccin mocha",
		"dot": {
			"bg": "#181825",
			"fg": "#cdd6f4",
			"accent": "#cba6f7"
		}
	},
	{
		"id": "dracula",
		"label": "dracula",
		"dot": {
			"bg": "#282a36",
			"fg": "#f8f8f2",
			"accent": "#c5a1fa"
		}
	},
	{
		"id": "gruvbox-dark",
		"label": "gruvbox dark",
		"dot": {
			"bg": "#282828",
			"fg": "#ebdbb2",
			"accent": "#dc9eae"
		}
	},
	{
		"id": "monokai-pro",
		"label": "monokai pro",
		"dot": {
			"bg": "#2d2a2e",
			"fg": "#fcfcfa",
			"accent": "#b5a8f3"
		}
	},
	{
		"id": "one-dark",
		"label": "one dark",
		"dot": {
			"bg": "#21252b",
			"fg": "#cacfd7",
			"accent": "#d296e4"
		}
	},
	{
		"id": "rose-pine",
		"label": "rose pine",
		"dot": {
			"bg": "#191724",
			"fg": "#e0def4",
			"accent": "#c4a7e7"
		}
	},
	{
		"id": "solarized-dark",
		"label": "solarized dark",
		"dot": {
			"bg": "#002b36",
			"fg": "#c5cdce",
			"accent": "#a6aadb"
		}
	},
	{
		"id": "tokyonight-night",
		"label": "tokyonight night",
		"dot": {
			"bg": "#16161e",
			"fg": "#c0caf5",
			"accent": "#bb9af7"
		}
	},
	{
		"id": "tokyonight-storm",
		"label": "tokyonight storm",
		"dot": {
			"bg": "#1f2335",
			"fg": "#c7d0f6",
			"accent": "#bb9bf7"
		}
	}
]
;
